project_id = "otibsrdecgygoeshfoho"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://localhost:3000"

[functions.send-webhook]
verify_jwt = false

[functions.track-conversion]
verify_jwt = false

[functions.trigger-order-webhooks]
verify_jwt = false

[functions.enhance-html]
verify_jwt = false

[functions.check-api-key]
verify_jwt = false

[functions.check-fraudcheck-key]
verify_jwt = false

[functions.test-fraudcheck]
verify_jwt = false

[functions.courier-create-order]
verify_jwt = false

[functions.courier-sync-status]
verify_jwt = false

[functions.courier-webhook]
verify_jwt = false

[functions.pathao-auth]
verify_jwt = false

[functions.pathao-locations]
verify_jwt = false

[functions.optimize-image]
verify_jwt = false

[functions.track-event]
verify_jwt = false

[functions.messenger-webhook]
verify_jwt = false

[functions.messenger-send]
verify_jwt = false

[functions.facebook-pages]
verify_jwt = false

[functions.ai-reply-suggest]
verify_jwt = false

[functions.provision-shop]
verify_jwt = false

[functions.send-invitation-email]
verify_jwt = false
